version: 0.0
os: linux
files:
  - source: /
    destination: /var/webapps/basic-api
hooks:
  BeforeInstall:
    - location: provision.sh
      timeout: 600
  ApplicationStart:
    - location: aws_deploy.sh
      timeout: 600
  ValidateService:
    - location: validate.sh
      timeout: 600
#permissions:
#  - object: /var/webapps/basic-api/aws_deploy.sh
#    mode: 755
#  - object: /var/webapps/basic-api/validate.sh
#    mode: 755
