version: 0.0
os: linux
files:
  - source: /
    destination: /var/webapps/basic-api
hooks:
  ApplicationStart:
    - location: /var/webapps/aws_deploy.sh
      timeout: 360
  ValidateService:
    - location: /var/webapps/validate.sh
      timeout: 360
